# Generated by Django 4.2.4 on 2025-03-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
